### PR TITLE
Make Gitea up-to-date with the original source

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
Before we modify the original source to make the custom authentication endpoints, I think we should be up-to-date with the original source.
We're hundreds of commits behind the original source.

### CODE REVIEW

**Comment by kasbah** [comment]
Good idea. Have you checked this still works with current kitspace-using-gitea?

**Comment by AbdulrhmnGhanem** [comment]
# Test procedure

- Modified `.gitsubmodule` to use the master branch from `go-gitea`.
- Ran `git submodule update --init`
- Pruned all images with `docker-compose rm`
- Ran `docker-compose build` , the output as expected:

    ``` plain
    nginx uses an image, skipping
    postgres uses an image, skipping
    Building gitea
    ...
    ```

- Both `gitea.Kitspace:3000` and Kitspace:3000 are up and working as before.
- For the future, I think it's a good idea to add some integration tests to test whether the Gitea API is adhering to the interface expected by Kitspace. I think I was an easy migration because the frontend isn't really calling anything from Gitea yet. :sweat_smile:
- `.gitsubmodule` is back to `kitspace/gitea`

**Comment by kasbah** [comment]
I think your procedure must have a problem somewhere. It should have failed as go-gitea master wouldn't have the mods I made to make it work with the kitspace frontend. I am using the [kitspace branch](https://github.com/kitspace/gitea/tree/kitspace). I think it's best to try and rebase that branch onto latest gitea master so we have our mods up on the top of the history.

Is it ok if I take on doing this update so you can focus on the other work?

**Comment by AbdulrhmnGhanem** [comment]
OK, fine.

**Comment by AbdulrhmnGhanem** [comment]
Yet I am confused now. Shouldn't gitsubmodule pull the default branch from https://github.com/kitspace/gitea which is the master?
The master branch of this fork doesn't have your modification!

**Comment by kasbah** [comment]
No, it grabs a specific commit id, which currently ffb9f26672cdf2e2ffdca62dbbcaa5d433a3a627. That's probably the flaw in your procedure actually, it probably just went ahead and grabbed the same commit from our repo? Git submodules are confusing at the best of times... they never quite seem to do what you expect.

**Comment by kasbah** [comment]
I'll switch to using the master branch on here though, to make it slightly less confusing.

**Comment by AbdulrhmnGhanem** [comment]
I can't recall the commit SHA. Anyways it's yours now. :grin:

**Comment by kasbah** [comment]
You can see it in git or when you visit kitspace-using-gitea on github:

image


Anyway, yeah, I'm just testing the update now.

**Pull request merged**
