### PR TITLE
Merge remote-tracking branch `upstream/main` into `kitspace/master`

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**

### CODE REVIEW

**Comment by kasbah** [comment]
As long as it's all tested and working please rebase all our changes onto the updated main and reset our master to that. That way it's easier to see what our changes are.

**Comment by AbdulrhmnGhanem** [comment]
Rebased on master, and reset master.

**Comment by kasbah** [comment]
Something went wrong I think. We should only be ahead of upstream main with a few commits, not behind and especially not ahead so many commits:

> image

**Comment by AbdulrhmnGhanem** [comment]
> Something went wrong I think. We should only be ahead of upstream main with a few commits, not behind and especially not ahead so many commits.

I tried again in https://github.com/kitspace/gitea/tree/rebase-3, it fixed the history, waiting for tests to pass then I will reset master to rebase-3.

**Comment by AbdulrhmnGhanem** [comment]
Passed  https://github.com/kitspace/kitspace-v2/runs/3302988331.

**Pull request closed without merging**
