### PR TITLE
Fix missing `original_url` for migrated repos

### LINKED ISSUE #15: Missing `original_url` for migrated repos
The response for `GET repos/{owner}/{repo}` has the `original_url: ''`, I don't remember if this was always the case or not.

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
Fixes #15
##

**NOTE**: Comparing against `update-gitea` not master to make the review easier, merge this first then merge #17.

### CODE REVIEW

**Comment by kasbah** [comment]
This seems like something we should also pull-request upstream right? If so, can you do that please?

**Comment by AbdulrhmnGhanem** [comment]
> This seems like something we should also pull-request upstream right?

No, I made this mistake while adding support for querying the migration progress status which isn't upstream.

**Comment by kasbah** [comment]
Did you try and upstrean that, can you link it please? That was a bigger API change anyway. This one just seems like a bug fix.

**Comment by AbdulrhmnGhanem** [comment]
> Did you try and upstrean that, can you link it please? 

Not yet. There's a problem with URL validation I will fix it then upstream the whole thing.

**Comment by kasbah** [comment]
But there's no problem with this fix right? So can you pull-request it upstream in the meantime?

**Comment by AbdulrhmnGhanem** [comment]
The bug isn't upstream.
> I made this mistake while adding support for querying the migration progress status which isn't upstream.

**Comment by kasbah** [comment]
Oh, I see now. I thought you meant your mistake was trying to upstream it.

**Pull request merged**
